In [11]:
%pip uninstall -y gym
%pip install -q -U gymnasium
%pip install -q -U gymnasium[classic_control,box2d,atari,accept-rom-license]

Found existing installation: gym 0.26.2
Uninstalling gym-0.26.2:
  Successfully uninstalled gym-0.26.2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 49.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 81.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 73.7 MB/s eta 0:00:00


In [2]:
import gym
env=gym.make("CartPole-v1",render_mode="rgb_array")

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.


In [3]:
obs, info=env.reset(seed=42)

In [4]:
obs

array([ 0.0273956 , -0.00611216,  0.03585979,  0.0197368 ], dtype=float32)

In [5]:
info

{}

In [8]:
img=env.render()
img.shape

(400, 600, 3)

In [9]:
env.action_space

Discrete(2)

In [14]:
obs, info=env.reset(seed=42)
action=1
obs ,reward, done, truncate, info=env.step(action)
obs

array([ 0.02727336,  0.18847767,  0.03625453, -0.26141977], dtype=float32)

In [12]:
import gymnasium as gym
env=gym.make("CartPole-v1",render_mode="rgb_array")

In [15]:
action=1

In [16]:
obs, reward, done, truncated, info=env.step(action)

In [17]:
obs

array([ 0.03104291,  0.38306385,  0.03102613, -0.5424507 ], dtype=float32)

In [18]:
reward

1.0

In [19]:
done

False

In [20]:
truncated

False

In [21]:
info

{}

In [22]:
def basic_policy(obs):
  angle=obs[2]
  return 0 if angle <0 else 1

totals=[]
for episode in range(500):
  episode_rewards=0
  obs, info=env.reset()
  for step in range(200):
    action=basic_policy(obs)
    obs, reward, done, truncated, info=env.step(action)
    episode_rewards+=reward
    if done or truncated:
      break;
  totals.append(episode_rewards)

In [23]:
import numpy as np
np.mean(totals),np.std(totals),min(totals),max(totals)

(np.float64(42.18), np.float64(9.015963620157304), 24.0, 72.0)